#!/usr/bin/env bash
# Phase 36 — Planetary Raft consensus mesh orchestrator (Ubuntu-optimized).
#
# Provisions / scales consensus quorum nodes from geographic traffic shifts.
# Complements deploy_planetary_mesh.sh (failover) with Raft-over-WebRTC quorum.
#
# Usage:
#   sudo ./scripts/deploy_consensus_mesh.sh --provision
#   ./scripts/deploy_consensus_mesh.sh --scale --traffic 'us-east:40,eu-west:35,ap-south:25'
#   DRY_RUN=1 ./scripts/deploy_consensus_mesh.sh --status
#
# Env:
#   CONSENSUS_STATE_DIR   default /var/lib/status-consensus-mesh
#   CONSENSUS_QUORUM_SIZE default 3
#   CONSENSUS_REGION      default local
#   STATUS_API_BASE       optional API for register/propose
#   DOCKER_IMAGE          default status-consensus-node:36
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE_DIR="${CONSENSUS_STATE_DIR:-/var/lib/status-consensus-mesh}"
QUORUM="${CONSENSUS_QUORUM_SIZE:-3}"
REGION="${CONSENSUS_REGION:-local}"
DRY_RUN="${DRY_RUN:-0}"
DOCKER_IMAGE="${DOCKER_IMAGE:-status-consensus-node:36}"
COMPOSE_FILE="${CONSENSUS_COMPOSE_FILE:-$STATE_DIR/docker-compose.consensus.yml}"

log() { echo "[consensus-mesh $(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }
die() { log "ERROR: $*"; exit 1; }

ensure_ubuntuish() {
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    case "${ID:-}:${ID_LIKE:-}" in
      ubuntu:*|*:ubuntu*|debian:*|*:debian*) ;;
      *) log "WARN: optimized for Ubuntu; ID=${ID:-unknown}" ;;
    esac
  fi
}

need() { command -v "$1" >/dev/null 2>&1 || die "Missing $1 (Ubuntu: apt install $2)"; }

write_compose() {
  local n="$1"
  mkdir -p "$STATE_DIR"
  cat > "$COMPOSE_FILE" <<EOF
# Auto-generated by deploy_consensus_mesh.sh — Raft quorum size=$n region=$REGION
services:
EOF
  local i
  for ((i=1; i<=n; i++)); do
    cat >> "$COMPOSE_FILE" <<EOF
  consensus-$i:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    environment:
      CONSENSUS_NODE_ID: ${REGION}-n${i}
      CONSENSUS_REGION: ${REGION}
      CONSENSUS_QUORUM_SIZE: "${n}"
      MCP_PROTOCOL_VERSION: "2026-07-28"
    ports:
      - "$((7100 + i)):8080"
    labels:
      status.mesh: consensus
      status.region: ${REGION}
EOF
  done
  log "Wrote $COMPOSE_FILE (nodes=$n)"
}

provision() {
  local n="${1:-$QUORUM}"
  (( n >= 3 )) || die "Quorum must be >= 3 (got $n)"
  write_compose "$n"
  echo "$n" > "$STATE_DIR/quorum_size"
  echo "$REGION" > "$STATE_DIR/region"

  if [[ "$DRY_RUN" == "1" ]]; then
    log "DRY_RUN: would docker compose -f $COMPOSE_FILE up -d"
    return 0
  fi

  if command -v docker >/dev/null 2>&1; then
    # Prefer echo image if custom image missing — use agent-swarm as stand-in
    if ! docker image inspect "$DOCKER_IMAGE" >/dev/null 2>&1; then
      log "Image $DOCKER_IMAGE missing — using deploy/serverless/agent-swarm as stub"
      if [[ -f "$ROOT/deploy/serverless/agent-swarm/Dockerfile" ]]; then
        docker build -t "$DOCKER_IMAGE" "$ROOT/deploy/serverless/agent-swarm" || true
      fi
    fi
    docker compose -f "$COMPOSE_FILE" up -d
    log "Quorum provisioned: $n nodes in $REGION"
  else
    log "WARN: docker not installed — compose written only (apt install docker.io docker-compose-v2)"
  fi

  if [[ -n "${STATUS_API_BASE:-}" ]]; then
    curl -sS -X POST "${STATUS_API_BASE%/}/api/v2/consensus/elect" \
      -H "Content-Type: application/json" \
      -d '{}' >/dev/null || log "WARN: elect API unreachable"
  fi
}

scale_from_traffic() {
  local traffic="${1:-}"
  [[ -n "$traffic" ]] || die "Pass --traffic 'region:weight,...'"

  # Parse weights → recommend quorum via simple log2 heuristic (mirrors backend)
  local regions=0
  IFS=',' read -r -a parts <<< "$traffic"
  regions=${#parts[@]}
  local target
  target=$(python3 - <<PY
import math
regions=$regions
print(max(3, min(9, 1 + 2 * math.ceil(math.log2(max(2, regions+1))))))
PY
)
  log "Traffic map=$traffic → target quorum=$target"
  # Prefer heaviest region label for local compose
  local top_region="$REGION" top_w=0
  local p r w
  for p in "${parts[@]}"; do
    r="${p%%:*}"
    w="${p##*:}"
    if (( w > top_w )); then top_w=$w; top_region=$r; fi
  done
  REGION="$top_region"
  provision "$target"

  mkdir -p "$STATE_DIR"
  echo "$traffic" > "$STATE_DIR/last_traffic_map"
  echo "$target" > "$STATE_DIR/quorum_size"
}

status() {
  mkdir -p "$STATE_DIR" 2>/dev/null || STATE_DIR="/tmp/status-consensus-mesh"
  log "state_dir=$STATE_DIR"
  [[ -f "$STATE_DIR/quorum_size" ]] && log "quorum=$(cat "$STATE_DIR/quorum_size")"
  [[ -f "$STATE_DIR/region" ]] && log "region=$(cat "$STATE_DIR/region")"
  [[ -f "$STATE_DIR/last_traffic_map" ]] && log "traffic=$(cat "$STATE_DIR/last_traffic_map")"
  if [[ -f "$COMPOSE_FILE" ]] && command -v docker >/dev/null 2>&1; then
    docker compose -f "$COMPOSE_FILE" ps || true
  fi
  if [[ -n "${STATUS_API_BASE:-}" ]]; then
    curl -sS "${STATUS_API_BASE%/}/api/v2/consensus/status" || true
    echo
  fi
}

main() {
  ensure_ubuntuish
  need curl curl
  mkdir -p "$STATE_DIR" 2>/dev/null || STATE_DIR="/tmp/status-consensus-mesh"
  mkdir -p "$STATE_DIR"
  COMPOSE_FILE="${CONSENSUS_COMPOSE_FILE:-$STATE_DIR/docker-compose.consensus.yml}"

  local cmd="${1:---status}"
  case "$cmd" in
    --provision) provision "${2:-$QUORUM}" ;;
    --scale)
      shift
      local traffic=""
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --traffic) traffic="$2"; shift 2 ;;
          *) traffic="$1"; shift ;;
        esac
      done
      scale_from_traffic "$traffic"
      ;;
    --status) status ;;
    --help|-h) sed -n '1,35p' "$0" ;;
    *) die "Unknown: $cmd (use --provision|--scale|--status)" ;;
  esac
}

main "$@"
