/**
 * Phase 40 — Autonomous code synthesis → sandboxed GitHub PR pipeline.
 * Extends Phase 23 self-healing into draft/test/PR flow (never force-pushes; dry-run by default).
 */

import crypto from 'crypto';
import { execFile } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../../utils/logger.js';
import { AppError } from '../../utils/errors.js';
import { assertAgentsNotKilled } from '../security/globalKillSwitchService.js';
import { appendAuditEvent } from '../security/immutableAuditLedger.js';
import { generatePatchProposal, fingerprintError } from '../selfHealing/selfHealingPatchEngine.js';

const execFileAsync = promisify(execFile);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../../../');
const WORK_DIR = process.env.CODE_SYNTHESIS_WORKDIR
  ?? path.join(ROOT, 'data/code-synthesis');

const ENABLED = () => process.env.AUTOPILOT_GITHUB_SYNTHESIS === 'true';
const DRY_RUN = () => process.env.CODE_SYNTHESIS_DRY_RUN !== 'false'; // default dry-run

/**
 * Draft a minor feature / refactor patch proposal (sandboxed, no network until PR step).
 */
export async function synthesizeCodeChange({
  title,
  description,
  kind = 'refactor',
  targetPaths = [],
  errorEvent = null,
  requestedBy = 'puppeteer',
} = {}) {
  assertAgentsNotKilled();

  const id = crypto.randomUUID();
  const fingerprint = errorEvent
    ? fingerprintError(errorEvent, { path: errorEvent.route })
    : crypto.createHash('sha256').update(`${title}:${kind}`).digest('hex').slice(0, 16);

  let healingPatch = null;
  if (errorEvent) {
    healingPatch = await generatePatchProposal(errorEvent);
  }

  const branch = `autopilot/${kind}-${fingerprint}`;
  const body = buildPrBody({ title, description, kind, healingPatch, fingerprint, requestedBy });

  // Sandboxed file artifact (never writes into tracked source unless apply is requested)
  await fs.mkdir(WORK_DIR, { recursive: true });
  const artifactPath = path.join(WORK_DIR, `${id}.patch.md`);
  const artifact = {
    id,
    fingerprint,
    branch,
    title: title ?? `Autopilot ${kind}: ${fingerprint}`,
    description: description ?? '',
    kind,
    targetPaths,
    healingPatch,
    body,
    createdAt: new Date().toISOString(),
    status: 'drafted',
  };
  await fs.writeFile(artifactPath, renderArtifactMarkdown(artifact), 'utf8');

  await appendAuditEvent({
    type: 'code_synthesis.draft',
    actor: requestedBy,
    action: 'synthesize',
    decision: 'drafted',
    metadata: { id, branch, kind, dryRun: DRY_RUN() },
  });

  logger.info(`[CodeSynthesis] drafted ${id.slice(0, 8)} branch=${branch} dryRun=${DRY_RUN()}`);
  return { ...artifact, artifactPath };
}

function buildPrBody({ title, description, kind, healingPatch, fingerprint, requestedBy }) {
  return [
    '## Summary',
    `- Autopilot ${kind} proposal (${fingerprint})`,
    description ? `- ${description}` : null,
    healingPatch
      ? `- Self-healing patch type: \`${healingPatch.patchType}\` for \`${healingPatch.routePattern}\``
      : null,
    '',
    '## Test plan',
    '- [ ] `cd backend && npm test`',
    '- [ ] Confirm no secrets in diff',
    '- [ ] Human review before merge (required)',
    '',
    `Requested by: \`${requestedBy}\``,
    '',
    '> Generated by Status Phase 40 code synthesis. Default mode is dry-run; enable `AUTOPILOT_GITHUB_SYNTHESIS=true` and unset dry-run to open a real PR.',
  ]
    .filter(Boolean)
    .join('\n');
}

function renderArtifactMarkdown(artifact) {
  return [
    `# ${artifact.title}`,
    '',
    artifact.body,
    '',
    '```json',
    JSON.stringify(
      {
        id: artifact.id,
        branch: artifact.branch,
        kind: artifact.kind,
        targetPaths: artifact.targetPaths,
        healingPatch: artifact.healingPatch,
      },
      null,
      2,
    ),
    '```',
    '',
  ].join('\n');
}

/**
 * Run lightweight validation gate (tests) before any PR open.
 */
export async function runSynthesisTestGate({ timeoutMs = 120_000 } = {}) {
  assertAgentsNotKilled();
  try {
    const { stdout, stderr } = await execFileAsync('npm', ['test'], {
      cwd: path.join(ROOT, 'backend'),
      timeout: timeoutMs,
      env: { ...process.env, NODE_ENV: 'test' },
    });
    return { ok: true, stdout: stdout.slice(-2000), stderr: stderr.slice(-500) };
  } catch (err) {
    return {
      ok: false,
      error: err.message,
      stdout: err.stdout?.toString?.()?.slice(-2000),
      stderr: err.stderr?.toString?.()?.slice(-2000),
    };
  }
}

/**
 * Open a GitHub PR via `gh` (requires network + auth). Blocked unless synthesis enabled.
 * Never uses --force or skips hooks.
 */
export async function openSynthesisPullRequest(artifact, { runTests = true } = {}) {
  assertAgentsNotKilled();

  if (!ENABLED()) {
    return {
      opened: false,
      dryRun: true,
      reason: 'AUTOPILOT_GITHUB_SYNTHESIS not enabled',
      artifact,
      suggestedCommands: [
        `gh pr create --title "${artifact.title}" --body-file ${artifact.artifactPath}`,
      ],
    };
  }

  if (DRY_RUN()) {
    return {
      opened: false,
      dryRun: true,
      reason: 'CODE_SYNTHESIS_DRY_RUN (default true)',
      artifact,
      suggestedCommands: [
        'export AUTOPILOT_GITHUB_SYNTHESIS=true CODE_SYNTHESIS_DRY_RUN=false',
        `gh pr create --title ${JSON.stringify(artifact.title)} --body-file ${artifact.artifactPath}`,
      ],
    };
  }

  if (runTests) {
    const gate = await runSynthesisTestGate();
    if (!gate.ok) {
      throw new AppError(`Synthesis test gate failed: ${gate.error}`, 422, 'SYNTHESIS_TEST_FAILED');
    }
  }

  // Create branch + empty commit note only if working tree allows — prefer documenting PR from artifact
  try {
    const bodyArgs = [
      'pr',
      'create',
      '--title',
      artifact.title,
      '--body',
      artifact.body,
      '--label',
      'autopilot,needs-human-review',
    ];
    const { stdout } = await execFileAsync('gh', bodyArgs, {
      cwd: ROOT,
      timeout: 60_000,
    });
    const url = stdout.trim();
    await appendAuditEvent({
      type: 'code_synthesis.pr_opened',
      actor: 'autopilot',
      action: 'gh_pr_create',
      decision: 'opened',
      metadata: { id: artifact.id, url },
    });
    return { opened: true, dryRun: false, url, artifact };
  } catch (err) {
    logger.warn(`[CodeSynthesis] gh pr create failed: ${err.message}`);
    throw new AppError(
      `GitHub PR create failed: ${err.message}. Ensure gh is authenticated and a branch with changes exists.`,
      502,
      'SYNTHESIS_PR_FAILED',
    );
  }
}

/**
 * End-to-end: draft → test gate → optional PR.
 */
export async function runAutonomousSynthesisPipeline(args = {}) {
  const artifact = await synthesizeCodeChange(args);
  const tests = await runSynthesisTestGate();
  const pr = await openSynthesisPullRequest(artifact, { runTests: false });
  return { artifact, tests, pr };
}

export function getCodeSynthesisConfig() {
  return {
    enabled: ENABLED(),
    dryRun: DRY_RUN(),
    workDir: WORK_DIR,
    requiresHumanReview: true,
    forbidsForcePush: true,
  };
}
