/**
 * Phase 43 — Runtime meta-compilation daemon (Node orchestration).
 * Analyzes bottlenecks, drafts sandboxed rewrites, optional artifact write.
 * Never hot-swaps production unless META_COMPILER_HOT_SWAP=true + alignment ok.
 */

import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../../utils/logger.js';
import { AppError } from '../../utils/errors.js';
import { assertAgentsNotKilled } from '../security/globalKillSwitchService.js';
import { appendAuditEvent } from '../security/immutableAuditLedger.js';
import { observeAlignmentTurn } from '../alignment/syntheticAlignmentBench.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../../../');
const ARTIFACT_DIR = process.env.META_COMPILER_DIR
  ?? path.join(ROOT, 'data/meta-compiler');

const DENY_PREFIXES = [
  '.env',
  'backend/src/middleware/auth',
  'backend/src/services/security/globalKillSwitch',
  'backend/src/services/governance',
];

const HOT_SWAP = () => process.env.META_COMPILER_HOT_SWAP === 'true';
const ENABLED = () => process.env.META_COMPILER_ENABLED !== 'false';

/**
 * Analyze execution metrics → bottlenecks.
 */
export function analyzeBottlenecks(metrics = {}) {
  const pathHint = metrics.path
    ?? (String(metrics.json ?? '').includes('ContextEngine')
      ? 'backend/src/services/context/ContextEngine.js'
      : 'backend/src/services/ai/agentTools.js');
  const cpu = Number(metrics.cpu_pct ?? 50);
  const p99 = Number(metrics.p99_ms ?? 40);
  return [{
    hotspotPath: pathHint,
    cpuPct: cpu,
    p99Ms: p99,
    rewriteSuggested: cpu > 70 || p99 > 80,
  }];
}

function assertPathAllowed(targetPath) {
  const p = String(targetPath);
  for (const deny of DENY_PREFIXES) {
    if (p.includes(deny)) {
      throw new AppError(`Meta-compiler deny: ${deny}`, 403, 'META_ALIGNMENT_DENY');
    }
  }
}

/**
 * Propose a sandboxed rewrite stub (does not modify source tree).
 */
export async function proposeSandboxedRewrite(bottleneck) {
  assertAgentsNotKilled();
  if (!ENABLED()) throw new AppError('Meta-compiler disabled', 503, 'META_DISABLED');
  assertPathAllowed(bottleneck.hotspotPath);

  const stub = [
    `// meta-compiler sandbox stub for ${bottleneck.hotspotPath}`,
    '// Generated by Phase 43 daemon — NOT applied to production by default.',
    'export function hotPathOptimized() { return { ok: true, sandboxed: true }; }',
    '',
  ].join('\n');

  const commitment = crypto.createHash('sha256').update(stub).digest('hex');
  const proposal = {
    proposalId: `meta-${commitment.slice(0, 12)}`,
    targetPath: bottleneck.hotspotPath,
    sandboxed: true,
    alignmentOk: true,
    hotSwapAllowed: false,
    sourceStub: stub,
    commitment,
    createdAt: new Date().toISOString(),
  };

  // Alignment gate on generated stub text
  const align = observeAlignmentTurn({
    agentId: 'meta-compiler',
    prompt: `rewrite ${bottleneck.hotspotPath}`,
    response: stub,
  });
  if (align.turn.ethical && !align.turn.ethical.aligned) {
    proposal.alignmentOk = false;
    throw new AppError('Meta-compiler alignment failed', 403, 'META_ALIGNMENT_FAIL');
  }

  await appendAuditEvent({
    type: 'meta_compiler.propose',
    actor: 'meta-compiler',
    action: 'propose',
    decision: 'sandboxed',
    metadata: { proposalId: proposal.proposalId, target: proposal.targetPath },
  });

  return proposal;
}

/**
 * Compile (write artifact only). Hot-swap of live binaries is explicitly gated.
 */
export async function sandboxCompile(proposal, { allowHotSwap = false } = {}) {
  assertAgentsNotKilled();
  if (!proposal?.sandboxed || !proposal.alignmentOk) {
    throw new AppError('Sandbox/alignment gate failed', 403, 'META_SANDBOX_DENY');
  }
  if (allowHotSwap || HOT_SWAP()) {
    if (!proposal.hotSwapAllowed && !HOT_SWAP()) {
      throw new AppError('Hot-swap not permitted', 403, 'META_HOTSWAP_DENY');
    }
    // Even when env set, we still only write artifacts — never patch live modules in-process.
    logger.warn('[MetaCompiler] HOT_SWAP requested — artifact only; no live module patch');
  }

  await fs.mkdir(ARTIFACT_DIR, { recursive: true });
  const artifactPath = path.join(ARTIFACT_DIR, `${proposal.proposalId}.js`);
  await fs.writeFile(artifactPath, proposal.sourceStub, 'utf8');

  await appendAuditEvent({
    type: 'meta_compiler.compile',
    actor: 'meta-compiler',
    action: 'sandbox_compile',
    decision: 'artifact',
    metadata: { proposalId: proposal.proposalId, artifactPath },
  });

  logger.info(`[MetaCompiler] artifact ${proposal.proposalId} → ${artifactPath}`);
  return {
    artifactPath,
    applied: false,
    hotSwap: false,
    zeroTrust: true,
  };
}

/**
 * Daemon tick: analyze → propose → compile (sandbox).
 */
export async function runMetaCompilerTick(metrics = {}) {
  const bottlenecks = analyzeBottlenecks(metrics);
  const actions = [];
  for (const b of bottlenecks) {
    if (!b.rewriteSuggested) {
      actions.push({ hotspot: b.hotspotPath, status: 'skip_healthy' });
      continue;
    }
    try {
      const proposal = await proposeSandboxedRewrite(b);
      const compiled = await sandboxCompile(proposal, { allowHotSwap: false });
      actions.push({ hotspot: b.hotspotPath, status: 'artifact', proposalId: proposal.proposalId, compiled });
    } catch (err) {
      actions.push({ hotspot: b.hotspotPath, status: 'denied', error: err.message });
    }
  }
  return {
    daemon: 'meta-compiler/v1',
    native: {
      rust: 'native/meta_compiler',
      cpp: 'native/meta_compiler/include/status_meta_compiler.h',
    },
    actions,
  };
}

export function getMetaCompilerConfig() {
  return {
    enabled: ENABLED(),
    hotSwap: HOT_SWAP(),
    artifactDir: ARTIFACT_DIR,
    denyPrefixes: DENY_PREFIXES,
    zeroTrust: true,
    selfModifying: 'sandboxed_proposals_only',
  };
}
